### ISSUE TITLE
Bind dashboard to localhost only

### ISSUE THREAD

**Issue by elisiariocouto** [emqtt/emqttd_dashboard#50]
I want to put an nginx in front of the dashboard to enable HTTPS. Currently, we can configure the port to listen at, but we can't configure the network address.

**Comment by erylee** [comment]
Hi @elisiariocouto, please try:

```
{emqttd_dashboard, 18083, [
            {acceptors, 4},
            {max_clients, 512},
            {sockopts, [
                {ip, {127,0,0,1}}
            ]}
]}
```

**Comment by elisiariocouto** [comment]
Perfect, this works. Thank you, closing the issue

**Comment by pewh** [comment]
Hi @elisiariocouto, does nginx ssl termination is working on emq dashboard? I'm trying reverse proxy from localhost:18083 to example.com/admin, but the page is blank because JS is not loaded.

From the html source, it seems `/static/js/vendor.12345.js` is not loaded because URL rewrite issue. Would you kindly to share working nginx script on this? Thank you very much.

**Comment by elisiariocouto** [comment]
@pewh, I'm not doing SSL termination anymore but I was using a pretty standard nginx SSL configuration. What is the error that you're facing when loading the JS scripts?

**Comment by aapris** [comment]
I put dashboard to URL https://mqtt.example.org/emq/ and I have nginx configuration below. Everything seems to work.
```
server {
 ...
    location /emq/ {
        proxy_pass http://localhost:18083/;
    }
    location /static/ {
        proxy_pass http://localhost:18083/static/;
    }
    location /api/ {
        proxy_pass http://localhost:18083/api/;
    }
```

**Comment by emqplus** [comment]
@CrazyWisdom Please add docs for Nginx + EMQ Dashboard.
